### ISSUE TITLE
Triangulation method

### ISSUE THREAD

**Issue by niccle27** [lambdaloop/anipose#17]
Hello,

First of all, thank your for your incredible work. I was looking into your triangulation method though i couldn't really understand it... Could you describe the method you are using to triangulate with multiple views ? Are you using some RANSAC for filtering some bad tracking ? 

Thank you a lot for your time

**Comment by lambdaloop** [comment]
Hello @niccle27 ,

Anipose supports multiple triangulation options, including:
- plain triangulation using linear-least squares
- RANSAC
- our own constrained optimization framing with spatiotemporal constraints

We're working on a preprint which details these methods and compares their performance on multiple datasets.

**Comment by niccle27** [comment]
Hello @lambdaloop 
Thank you a lot for your reply!
I'm currently trying to understand your code to set those triangulation parameter properly.

Though by testing the differents functions of the anipose API, the calibration gave me the following result

```toml
[cam_0]
name = "1"
size = [ 1920, 1080,]
matrix = [ [ 1341.294113016525, 0.0, 959.5,], [ 0.0, 1341.294113016525, 539.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.07205439308266164, 0.0, 0.0, 0.0, 0.0,]
rotation = [ 0.009136216504817538, 0.03511747068734043, 0.0405268345500322,]
translation = [ -35.09658399674201, 6.625260161173124, -298.1691170878793,]

[cam_1]
name = "2"
size = [ 1920, 1080,]
matrix = [ [ 1317.194602329241, 0.0, 959.5,], [ 0.0, 1317.194602329241, 539.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.009832504731787133, 0.0, 0.0, 0.0, 0.0,]
rotation = [ -0.1633837957842965, -0.8982009987073111, 0.001370804330048589,]
translation = [ 589.1383573212819, -33.67420192984623, -30.829766699026,]
```
The intrinsic parameters seems alright, i'm quite surprised by the rotation/translation. What exactly is the reference coordinate system ? I was also wondering whether the calibration was happening pair by pair or is your script calibrating extrinsic parameters using the redundancies between views ? As i'm currently working on a 12 cameras views system, this might be of great help to me.
