### ISSUE TITLE
Consider using a conda config file for installation

### ISSUE THREAD

**Issue by jonnew** [lambdaloop/anipose#40]
Currently instructions indicate that deeplabcut should be installed as a pip dependency but don't go into how to get a CPU or GPU dlc version. DLC solved this by just making conda config files for both options. I've pasted a conda specification file that I used to install a anipose-modified GPU DLC installation. Might be useful to supply this (along with CPU version that I didn't make) for easy install.

``` yaml
# FIRST: INSTALL CORRECT DRIVER for GPU, see https://stackoverflow.com/questions/30820513/what-is-the-correct-version-of-cuda-for-my-nvidia-driver/30820690
#
# install: conda env create -f anipose.yaml 
# update:  conda env update -f anipose.yaml 
name: anipose
dependencies:
  - python=3.7
  - pip
  - tensorflow-gpu==1.13.1
  - cudnn=7
  - wxpython
  - jupyter
  - nb_conda
  - Shapely
  - ffmpeg
  - mayavi
  - pip:
    - deeplabcut
    - anipose
```
