### ISSUE TITLE
Camera offset

### ISSUE THREAD

**Issue by menor22** [lambdaloop/anipose#6]
Hi,

I decided to 'crop' my 3 cameras views (same camera and lenses) and I set exactly the same offset to each camera.
Should I precise the offset in my config.toml file if I redo the calibration?
Since the offset is exactly the same in each camera I guess that it's like having the full view of each camera or am I wrong?

Best,

Y

**Comment by lambdaloop** [comment]
Hi @menor22 ,

I haven't tried calibrating with cropped frames, it might work. Let me know if you try it out!

However, it is better to calibrate with the full view and crop only when recording, as calibration performs better on the full camera view. In addition, this allows you to reuse the same calibration videos with different cropping for behavior.

For specifying camera offsets when cropping for behavior recording, you can do so in the config.toml file.

An example configuration (for three cameras named "A", "B", and "C"):
```toml
[cameras.A]
offset = [36, 165] # x, y offset from top left corner

[cameras.B]
offset = [279, 310]

[cameras.C]
offset = [92, 98]
```

Let me know if that makes sense.
